### PR TITLE
WIP: Add chat app research and offline cache spec

### PR DESCRIPTION
**Pull request by Steven-Chan**
connect #64

### CODE REVIEW

**Comment by Steven-Chan** [comment]
@carmenlau  Last time I mentioned about making message in db a link list data structure, i.e. each message has a reference of next and/or previous message.

I find the message has a sequence already, so we can make use of window function to generate a table to find neighbouring message.

I tried with the following sql.

```sql
select _id, conversation, seq, first_value(seq) over w as next_seq, _created_at, first_value(_created_at) over w as next_time
from message
window w as (partition by conversation order by seq desc rows between 1 preceding and current row);
```

**Comment by chpapa** [comment]
Just want to reminded that for local store, besides finding message in sequence, it is possible for full text search. Might not have to consider it for now

**Comment by Steven-Chan** [comment]
This would probably useful for identifying if there are missing messages between two given messages.

The last time discussion was about how to determine when to fetch messages in client, when there are some old local cache in the client and just received newly fetched result.

Given that the developer want to call `load more` when user scroll to top of the list, when to call `load more`?

```
----  <-- this may be the point to call load more.
 ^
 |
 |  10 messages in local cache
 |
 v
----

(How can the developer tell this gap between the two messages? Maybe caused by a period of offline time, or just occasional bad network env.)

----   <-- this may be the point to call load more.
 ^
 |
 | 10 newly fetched message
 |
 v
----
```

**Comment by Steven-Chan** [comment]
Offline discussion @chpapa about how to keep and retrieve message history from db.

Current `message_history` table only keeps the changing history of a message.

We may make the `message_history` a complete journal, storing a `history sequence`, `message_id`, `action`(create/update/delete) , `data`(updated column and value). The concept is that this history table is able to generate a full message table.

So the client may keep the last fetched `history sequence` and then ask the server to fetch newer history and generate the latest snapshot of the message table.

We considered using postgresql materialized view, however seems postgresql does not provide incremental update, this may have performance issue. At this moment, we may just update the message table and history table within a transaction to keep the two table update to date.

**Comment by Steven-Chan** [comment]
After some offline discussion, we decided to implement a simpler cache with sync version first.

**Pull request closed without merging**
