### PR TITLE
Support for job queue

### PR DESCRIPTION
**Pull request by cheungpat**
connects #40

### CODE REVIEW

**Comment by cheungpat** [comment]
Would be great if there are feedback on this article, this is intentionally brief because I would like to gather more feedback before I give more concrete examples, feel free to ask for clarification if there is anything you want to know more : )

**Comment by chpapa** [comment]
Thanks @cheungpat ! I have a few thoughts after reading the PR.

1. I'm a bit confused on use cases between Job Queue and Async Cloud Functions. For example in the document, it said "send an email" "liking a post" as use cases for job queue, but I thought async cloud functions already serve the purpose? I think we need to identify the use cases, as we will also need to write guides and tell people which use cases to use which features.
1. I think some requirements are "good to have" and not a must in version one. Such as cancellation and retrying. (Of coz if do it in one go is easier, let's do it!)
1. I'm more inclined to use Redis (finally) for two reasons:
    1. Seems there are many other features on wish-list that will need Redis. Maybe we would need it anyway at some point.
    1. I'm worried that we will regret using PostgreSQL as queue just like all the trouble we have had using MySQL as queue before. It is not well understood on how to use PGSQL as queues, how to fix problems and tune for performance. In fact, even que author wrote `I don't recommend that you try to run Que in production yet` before and it seems not really popular anyway https://gist.github.com/chanks/7585810; In contrast we use redis as queue all the time, it's popular for the usage; I understand the implication is we might need to do multi-tenant for redis by namespace on application code, but feel like that's easier than troubleshooting at PGSQL for something we are not familiar with. We can use AOF instead of RDB for better persistence?
1. Will we plan to make it possible to enqueue job coded in JS from PY or vice-versa?

**Comment by cheungpat** [comment]
> it said "send an email" "liking a post" as use cases for job queue, but I thought async cloud functions already serve the purpose?

When you are talking about async cloud function I think you are talking about database hooks. Database hooks have support for async call but this capability is only supported in database hooks (e.g. lambda). I am not aware of a method to support a use case such as performing an async job after running a lambda function.

---

The quote in its entirety: 

> I don't recommend that you try to run Que in production yet - the multi-threaded worker pool in particular is still a bit twitchy - but I'm very interested in comments and suggestions on it. My goal is to make it as reliable as possible while keeping its current speed.

Since the author coded Que in Ruby and the cited problem is about multi-threaded worker pool, the problem isn’t really relevant for us.

---

> Will we plan to make it possible to enqueue job coded in JS from PY or vice-versa?

This will be supported.

**Comment by cheungpat** [comment]
> it said "send an email" "liking a post" as use cases for job queue, but I thought async cloud functions already serve the purpose?

When you are talking about async cloud function I think you are talking about database hooks. Database hooks have support for async call but this capability is only supported in database hooks (e.g. lambda). I am not aware of a method to support a use case such as performing an async job after running a lambda function.

---

The quote in its entirety: 

> I don't recommend that you try to run Que in production yet - the multi-threaded worker pool in particular is still a bit twitchy - but I'm very interested in comments and suggestions on it. My goal is to make it as reliable as possible while keeping its current speed.

Since the author coded Que in Ruby and the cited problem is about multi-threaded worker pool, the problem isn’t really relevant for us.

---

> Will we plan to make it possible to enqueue job coded in JS from PY or vice-versa?

This will be supported.

**Comment by chpapa** [comment]
> When you are talking about async cloud function I think you are talking about database hooks. Database hooks have support for async call but this capability is only supported in database hooks (e.g. lambda). I am not aware of a method to support a use case such as performing an async job after running a lambda function.

Understood. Than for consistent and simpler syntax, would it make more sense to just have lambda function support async? It could be a simple wrapper to job dispatch the function as a job? (And it also consistent with DB Hooks in terms of syntax)

> Since the author coded Que in Ruby and the cited problem is about multi-threaded worker pool, the problem isn’t really relevant for us.

My point being it doesn't seems the lib is popular, nor using PGSQL as job queue is well understood in general / in our experience.

**Pull request merged**
